name: Run Aozora Scraper Go

uses: actions/setup-go@v4
with:
  go-version: '^1.20'  # Ensure a modern Go version (e.g., 1.20.x)
  cache: true  # Enable caching to speed up builds

on:
  workflow_dispatch:  # 手動実行トリガー

jobs:
  execute-aozora-scraper:
    runs-on: ubuntu-latest

    steps:
    # リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # Goのセットアップ
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20  # 必要なGoのバージョン

    # 依存関係のインストール
    - name: Install dependencies
      run: go mod tidy

    # jobs/aozora_scraper.go の実行
    - name: Run Aozora Scraper
      run: go run jobs/aozora_scraper.go