name: Fetch Aozora Text

# on:
#   schedule:
#     - cron: '0 3 * * *' # 毎日12:00 JST
#   workflow_dispatch:

on:
  workflow_dispatch:  # 手動実行トリガー

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests beautifulsoup4

      - name: Fetch Aozora Bunko text
        run: |
          python3 scripts/fetch_aozora_text.py "https://www.aozora.gr.jp/cards/000020/files/2569_28291.html"

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Fetch Aozora text $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push origin HEAD